# features
# DYNAMIC_TAPPING_TERM_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes

# space savings
LTO_ENABLE = yes
MUSIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
