# features
# DYNAMIC_TAPPING_TERM_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
MOUSEKEY_ENABLE = no

# space savings
LTO_ENABLE = yes
MUSIC_ENABLE = no
CONSOLE_ENABLE = yes # TODO: tmp to debug TRRS disconnects
COMMAND_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
