JJ_SPLIT = no

# features
# DYNAMIC_TAPPING_TERM_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
LAYER_LOCK_ENABLE = no
CAPS_WORD_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

# space savings
LTO_ENABLE = yes
MUSIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
GRAVE_ESC_ENABLE = no

# gaming
DEBOUNCE_TYPE = asym_eager_defer_pk
SOCD_ENABLE = yes
