name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@ba76ce3d20f542d61c4c3d47c1d1d9e73b60a797
    with:
      qmk_repo: qmk/qmk_firmware
      # renovate: datasource=github-releases depName=qmk/qmk_firmware
      qmk_ref: 0.28.0

  date:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        id: date
        run: |
            echo "now=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_OUTPUT
    outputs:
      date: "${{ steps.date.outputs.now }}"

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@ba76ce3d20f542d61c4c3d47c1d1d9e73b60a797
    if: always() && !cancelled()
    needs: [build, date]
    with:
      release_name: "${{ needs.date.outputs.date }}"
#-${{ github.sha }}"
